### ISSUE TITLE
restore binary downloads from Download page

### ISSUE THREAD

**Issue by egonw** [bridgedb/BridgeDb#103]

**Comment by egonw** [comment]
They were still listed, but made it a bit more obvious on the website now. The bigger problem seems that people simply do not easily find the download page: I had two question recently about 1. binary downloads, 2. Maven Central info, both which are given on the Download page.

**Comment by DeniseSl22** [comment]
Isn't this also related to the releases tab on Github?

![image](https://user-images.githubusercontent.com/26277832/58015890-a8920580-7afc-11e9-8330-10e8443e5be9.png)

This only says "source code", which doesn't include the libraries itself right? Or are the libraries located somewhere else?

**Comment by egonw** [comment]
Good points. We need standard texts for this page and Zenodo to point to the website Download page, where people can find information on using binary distributions.

**Comment by egonw** [comment]
Done in 2.3.2
