### ISSUE TITLE
Check Jenkins; There are jobs failing consistently

### ISSUE THREAD

**Issue by nunogit** [bridgedb/BridgeDb#113]
Job failing

https://jenkins.bigcat.unimaas.nl/job/Metabolite%20ID%20Mapping%20Database/

**Comment by egonw** [comment]
The problem here turns out to be an upstream data error, which I just filed: https://github.com/ebi-chebi/ChEBI/issues/3591

cc @DeniseSl22

**Comment by egonw** [comment]
Fixed with https://github.com/bridgedb/create-bridgedb-metabolites/commit/018826407334873831d802ec95707d4d754d30e2
