### ISSUE TITLE
upgrade the test suite to JUnit5

### ISSUE THREAD

**Issue by egonw** [bridgedb/BridgeDb#115]
See https://junit.org/junit5/

**Comment by The-Marvex** [comment]
can we have this issue reopen, there are some packages whose test suite is needed to be updated. Or I can put a few more pull requests without this issue being reopened though.

**Comment by egonw** [comment]
Plz create a new branch. Yes, I noted the regressions (new fails of old tests). Basically, plz make a branch to develop is, and not make a pull request until you are done with everything. The pull request means it is ready

**Comment by The-Marvex** [comment]
Sorry about that, will take care of this from next time.

**Comment by egonw** [comment]
It gives you something to blog about ;) Seriously, this program is to learn you guys open source works. But it's so broad, and practices so diverse, that you learn from your "mistakes". Honestly, we've all been there, breaking stuff in "master". It's how you correct it, that defines how good a programmer you are.
