### ISSUE TITLE
Where is the BridgeDB ontology?

### ISSUE THREAD

**Issue by stain** [bridgedb/BridgeDb#13]
Two namespaces:
* http://openphacts.cs.man.ac.uk:9090/ontology/DataSource.owl#
* http://vocabularies.bridgedb.org/ops#

.. used for terms like `linksetJustification`, `subjectsDatatype` and more BridgeDb-specific like `hasIdentifiersOrgPattern` and `systemCode`.

I don't know if these two namespaces are the same or not. But the fact is that none of them resolve (both give 404), yet they are used here:

* http://www.openphacts.org/specs/2013/WD-datadesc-20130912/
* https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/develop/org.bridgedb.rdf/src/org/bridgedb/rdf/constants/BridgeDBConstants.java
* https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/develop/org.bridgedb.rdf/resources/IdentifiersOrgDataSource.ttl
* http://data.openphacts.org/1.5/ims/linksets/ConceptWiki/enzyme_expasy_org.ttl

Which one should it be? Has there been any attempt to create the ontology? Did `vocabularies.bridgedb.org` use to resolve to something else than an empty Drupal site?

**Comment by brenninc** [comment]
Hi Stain,

That was an issue that was not fully resolved.

Ideally they should be merged/changed into a single URL
There is no reason to have these different.

We originally started using:
http://openphacts.cs.man.ac.uk:9090/ontology/DataSource.owl#
as we had control of that

http://vocabularies.bridgedb.org/ops# fits more with the bridgedb branding but that is not a Manchester controlled site.

Christian

PS. I leave it to the current project team to pick the best way to clean what is agreeably a mess up.

**Comment by stain** [comment]
My draft - in case it doesn't exist:
* https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/develop/org.bridgedb.rdf/resources/ontology.ttl
* http://www.essepuntato.it/lode/owlapi/https://rawgit.com/bridgedb/BridgeDb/OpenPHACTS/develop/org.bridgedb.rdf/resources/ontology.ttl

I assume there that the 'datasource' ontology is separate.. yet there are things in the constants that sounds like they should are also be in bdb, e.g. [fullfillsLens](https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/develop/org.bridgedb.rdf/src/org/bridgedb/rdf/constants/BridgeDBConstants.java#L115)

**Comment by stain** [comment]
Thanks for the details, @brenninc.

OK, I'll complete the above ontology with the remaining datasource terms, and then we can call it the "Bridge DB ontology" - which match how it is described as "bdb" now. I might fix the odd spelling mistake.

I'll add  support to the BridgeDB RDF code for both the old and new namespaces - probably some kind of warning for old ones?

@egonw - would you be the right person to (eventually) modify what the http://vocabularies.bridgedb.org/ops# points to - or who should I ask?

```
vocabularies.bridgedb.org. 7200	IN	A	137.120.17.33
33.17.120.137.in-addr.arpa. 28800 IN	PTR	vocabularies.bigcat.maastrichtuniversity.nl.
```

**Comment by ariutta** [comment]
Great work! @stain, here's one more file with terms to check for consistency with the ontology:
[datasources_headers.txt](https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources_headers.txt). You probably know better than me what these terms should be, but let me know if I can help update the file to be consistent with the BridgeDb ontology.

**Comment by Christian-B** [comment]
While you are looking at this one thing to consider is the use of bridgeDB:hasUrlPattern and bridgeDB:hasUriPattern 
The difference was because a classic BridgeDb DataSource only has one UrlPattern.

May be worth considering a better clearer naming here,

as in
bridgeDB:DataSource_Chembl_Target a bridgeDB:DataSource ;
	bridgeDB:fullName "Chembl Target" ;
	bridgeDB:systemCode "ChemblTarget" ;
......
	bridgeDB:hasUrlPattern <http://data.kasabi.com/dataset/chembl-rdf/target/t$id> ;
	bridgeDB:hasUriPattern <http://chem2bio2rdf.org/chembl/resource/chembl_targets/$id> ;
	bridgeDB:hasUriPattern <http://linkedchemistry.info/chembl/target/t$id> ;
	bridgeDB:hasUriPattern <http://rdf.ebi.ac.uk/resource/chembl/target/$id> .
	bridgeDB:hasUrlPattern <http://data.kasabi.com/dataset/chembl-rdf/target/t$id> ;
	bridgeDB:hasUriPattern <http://chem2bio2rdf.org/chembl/resource/chembl_targets/$id> ;
	bridgeDB:hasUriPattern <http://linkedchemistry.info/chembl/target/t$id> ;

See:https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/master/org.bridgedb.rdf/resources/DataSource.ttl

**Comment by stain** [comment]
Thanks, I was a bit confused of `hasUrlPattern` vs `hasUriPattern` - is there still a need for the first one?

Perhaps the `primary` property on a pattern should be changed to a `hasPrimaryUriPattern` subproperty of `hasUriPattern`?

**Comment by stain** [comment]
My draft for the **BridgeDb DataSource ontology**:
https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/develop/org.bridgedb.rdf/resources/ontology.ttl

Visualized:
http://www.essepuntato.it/lode/owlapi/https://rawgit.com/bridgedb/BridgeDb/OpenPHACTS/develop/org.bridgedb.rdf/resources/ontology.ttl

@AlasdairGray - perhaps you could have a brief look? For the terms from [datadesc spec](http://www.openphacts.org/specs/2013/WD-datadesc-20130912/#bridgedb) I included the documentation as is, but added the friendly `skos:Concept` as range on `hasDataType`, `linksetJustification`, `objectsDatatype` and `subjectsDatatype` - as a kind of soft OWL/Full preventor as those would typically go towards other Classes and Properties.
 
TODO: `rdfs:comment` for the terms that are not in http://www.openphacts.org/specs/2013/WD-datadesc-20130912/#bridgedb (but then I would need to understand them all.. :-)

**Comment by Christian-B** [comment]
@stain Said "Perhaps the primary property on a pattern should be changed to a hasPrimaryUriPattern subproperty of hasUriPattern?"

That would have my vote if I still had one.

**Comment by stain** [comment]
So I changed `hasUrlPattern` to `hasPrimaryUriPattern`, a subproperty of `hasUriPattern`.

The `primary` property is [something different](https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/develop/org.bridgedb/src/org/bridgedb/DataSource.java#L815), that I'll leave as is.

**Comment by Christian-B** [comment]
The "primary" property was not used by OPS but included for backward comparability and to ensure that the OPS version still implemented the existing BridgeDb API's

**Comment by stain** [comment]
Assigned to @egonw who said he would have a look at publishing this at http://vocabularies.bridgedb.org/ops#

**Comment by egonw** [comment]
The result is online at the requested link. I started with the data source TTL files but in the end also included @stain's ontology.ttl terms.

@stain, is there anything left in the http://openphacts.cs.man.ac.uk:9090/ontology/DataSource.owl# namespace that was not in your ontology.ttl yet? If so, please reopen and let me know.

**Comment by egonw** [comment]
@ariutta, you want to use the ontology, you can perhaps use the https://github.com/alexmilowski/green-turtle HTML+RDFa parser in JavaScript?

**Comment by ariutta** [comment]
Thanks, Egon. I will use that. Should we also update the headers file for
datasources.txt?
