### ISSUE TITLE
xrefsBatch broken

### ISSUE THREAD

**Issue by AlexanderPico** [bridgedb/BridgeDb#137]
WikiPathways app for Cytoscape is getting a 404 for xrefsBatch query. Same from Swagger.  Maybe this didn’t survive the recent migration to AWS? 
https://www.bridgedb.org/swagger/#!/Genes/post_organism_xrefsBatch_systemCode
`"error": "no response from server"`

**Comment by nunogit** [comment]
@AlexanderPico moving shouldn't have this effect. Was this working before?
The batch call is known to have problems.

**Comment by nunogit** [comment]
@AlexanderPico the problem doesn't seem to be at the webservice level but with the call from swagger:

Running the command directly with curl returned an answer:

curl -X POST --header 'Content-Type: text/html' --header 'Accept: */*' -d '1234' 'https://webservice.bridgedb.org/Human/xrefsBatch/L'

1234	Entrez Gene	`X:U95626_rna3_at,T:GO:0005768,T:GO:0006935,T:GO:0071791,T:GO:0016021,T:GO:0006816,T:GO:0016020,X:8079401,T:GO:0004950,T:GO:0005886,T:GO:0004435,T:GO:0005887,T:GO:0007267,T:GO:0004871,S:Q38L21,Q:NM_000579,Q:NP_000570,Ag:A_23_P412321,X:206991_s_at,Pd:2L87,Pd:2MZX,T:GO:0019722,X:U83326_s_at,T:GO:0003779,T:GO:0005515,T:GO:0006968,T:GO:0002407,T:GO:0016493,Pd:2RRS,Pd:4MBS,T:GO:0007186,Pd:1OPW,Pd:1OPT,Q:NP_001093638,T:GO:0019957,Uc:uc062izs.1,X:16940182,Om:601373,Pd:1OPN,Om:609532,X:11730910_s_at,Wg:1234,Il:ILMN_2145033,T:GO:0023052,L:1234,Pd:1ND8,T:GO:0006952,Om:610379,T:GO:0004930,T:GO:0006955,T:GO:0006954,T:GO:0009986,T:GO:0007204,T:GO:2000110,Il:ILMN_1653395,X:X99393_s_at,X:8093298,T:GO:0030260,H:CCR5,U:Hs.450802,T:GO:0015026,T:GO:0070723,T:GO:0071222,Q:NM_001100168,Il:0006590601,T:GO:0016032,Pd:2RLL,T:GO:0005737,T:GO:0019064,T:GO:0070098,T:GO:0014808,Om:612522,T:GO:0000165,T:GO:0009897,T:GO:0007165,Pd:1NE0,X:11730909_s_at,T:GO:0007166,En:ENSG00000160791,X:11748062_s_at,T:GO:0001618,S:P51681,X:36724_s_at,Uc:uc062izt.1`

**Comment by nunogit** [comment]
Digging further, I found out that the Swagger GUI displays the call as a "POST", but sends it as a "OPTIONS" verb:

```
Request URL: https://webservice.bridgedb.org/Human/xrefsBatch/L
Request Method: OPTIONS
Status Code: 405 The method specified in the request is not allowed for the resource identified by the request URI
Remote Address: 35.157.241.83:443
Referrer Policy: no-referrer-when-downgrade
```

I would like to close this ticket and reopen it in swagger.
This is either a configuration file bug or a swagger javascript library bug, which implies we need to update the library.

Is there any further information you have that prevents from closing this one?
