### ISSUE TITLE
Fix unigene URI pattern for organism+clusterId

### ISSUE THREAD

**Issue by stain** [bridgedb/BridgeDb#14]
http://ops2.few.vu.nl/QueryExpander/dataSource/U

says:
```
primary UriPattern
    http://www.ncbi.nlm.nih.gov/UniGene/clust.cgi?UGID=1548618&SEARCH=$id
URI Pattern
    http://purl.uniprot.org/unigene/$id
idExample
    Hs.553708
```

but this URL only works for the example id, as http://www.ncbi.nlm.nih.gov/UniGene/clust.cgi?UGID=1548618&SEARCH=whatever will still show UGID:1548618 and just put `whatever` into the search box.

http://www.ncbi.nlm.nih.gov/UniGene/clust.cgi?ORG=Hs&CID=656875 does work correctly - but is not possible to use in BridgeDb as we don't support split identifiers.

The pattern http://purl.uniprot.org/unigene/Hs.553708 is valid and used internally by Uniprot, but does not resolve to anything meaningful ("Can't handle namespace: unigene"). 

Note that confusingly there is also the "Unigene number" - http://ops2.few.vu.nl/QueryExpander/dataSource/unigene which uses UGID - e.g. http://www.ncbi.nlm.nih.gov/UniGene/clust.cgi?UGID=$id

**Comment by Christian-B** [comment]
A few notes:
1. The OPS BridgeDb policy has been to support all known URI patterns regardless if the currently resolve or not.  After all they may be used in data and by users.

2. The "primary" UriPattern was picked by the following rules
      a. Use the one already used by BridgeDb
      b. Pick the one suggested by OPS

3. Split  identifiers is something not yet faced by the IMS.
If would probably have to be handled in the same way that xref prefixes are handled.
Ie by a layer on top of standard BridgeDb

See:
https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/master/org.bridgedb.rdf/src/org/bridgedb/rdf/pairs/RdfBasedCodeMapper.java

Changing IdSysCodePair  to handle the split/

Then change:
https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/master/org.bridgedb.uri.sql/src/org/bridgedb/sql/SQLUriMapper.java methods
toUris(IdSysCodePair ref) 
toIdSysCodePair(String uri) 

And any underlying database ect!

**Comment by stain** [comment]
Thanks for the pointers, @Christian-B! I think adding support for split identifiers is a bit overkill (unless we know of other such cases), and rather we can keep just http://purl.uniprot.org/unigene as the primary - which is what is needed to match the Uniprot linksets anyway.

I seriously don't hope the old format of http://www.ncbi.nlm.nih.gov/UniGene/clust.cgi?UGID=1548618&SEARCH=$id is used anywhere - as it would always return that Olfactory receptor.

I must admit I don't understand why Unigene has two sets of their own identifiers at all - the clusterId is not even consistent across organisms, so it's not like I can check at the mouse by changing to `ORG=Mm`.

See also http://www.ncbi.nlm.nih.gov/UniGene/help.cgi?item=FAQ#q12 - sadly the split clust.cgi format is the official link format here.


We can always request Uniprot if they could consider a redirect to UniGene's clust.cgi rather than the current 400 Bad Request after redirecting to http://www.uniprot.org/?query=purl:unigene/Hs.553708.

**Comment by stain** [comment]
I have asked Uniprot if they would consider redirect.

I have asked Unigene if they could add a ?ORGCID=Hs.12337 form.

**Comment by stain** [comment]
Just a note:

See below for feedback from NCBI - suggesting to traverse their API (they don't have any linksets) to get the mapping between UGID and Species/Cluster.

A quick check showed ~ 130.000 records (e.g. about 66 API calls) for generating the linkset for Human. 

We don't currently have a link between the Unigene and Unigene Number dataset - but I think that's not really needed as the Unigene Number (sadly?) is not so commonly used as the split Unigene "id"?

It might be needed in inverse though, if we want to include good outgoing links to Unigene, which I guess is valuable. I will let the domain experts within Open PHACTS chip in on this in a separate entry.

Theoretically - Without adding support for the split identifier we would then either create that linkset directly to the uniprot style URIs, or also have a second linkset from the ?split&format to the uniprot links..

> The work around is to parse out the mapping information (cluster accession to uid, for only the active entries) from summary.
> 
> For example, you can get the uid for a specific cluster by esearch:
> http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=unigene&term=Hs.2
> 
> The summary provides the mapping:
> http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=unigene&id=130645,310646
> 
> For all human records, you may want to do the following:
> 1. esearch:
> http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=unigene&term=human%5borgn%5d&usehistory=y&retmax=0
> 2. summary in batch of 2000:
> http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=unigene&WebEnv=NCID_1_299790388_130.14.22.215_9001_1438361135_65762357_0MetA0_S_MegaStore_F_1&query_key=1&retstart=0&retmax=2000
> 3. loop through the set increment the retstart value by 2000. Second iteration would be:
> http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=unigene&WebEnv=NCID_1_299790388_130.14.22.215_9001_1438361135_65762357_0MetA0_S_MegaStore_F_1&query_key=1&retstart=2000&retmax=2000
> 4. do so until Count from the first search step is reached
> 5. parse the output to get the <Id> and <CLUSTERID> value
> 
> If you are doing this from linux, you can install edirect package and do the whole task from a set of chained command (replaced the query with "human[orgn]":
> 
> esearch -db unigene -query "human[orgn]" |esummary |xtract -pattern DocumentSummary -element Id -sep "\t" -element CLUSTERID -sep "\n" >hs_ug_mapping_table
> 
> More information on eutils and edirect are at:
> http://www.ncbi.nlm.nih.gov/books/nbk25501
> 
> A webinar is listed here:
> https://www.youtube.com/user/NCBINLM

**Comment by stain** [comment]
The search pattern
http://www.ncbi.nlm.nih.gov/unigene?term=Hs.725124 also kind of works - but `?term=$id`  was already used by the Unigene number entry:

http://ops2.few.vu.nl/QueryExpander/dataSource/unigene

I will swap around so the `?UGID` is primary.

Would it work to have two sources both with ?term= ? but non-overlapping regexes, as they [have now](https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/develop/org.bridgedb.rdf/resources/IdentifiersOrgDataSource.ttl#L6095) ?

Then that could be a secondary pattern for the Unigene and remain for backward compat on Unigene Number.

**Comment by Christian-B** [comment]
1. Please be aware that the choice of primary URI was first based on backward compatibility to previous BridgeDb DataSource definitions, This could of course be broken if the current project people feel that is the best.

As for the same URI with non overlapping regex patterns this is handled well by the OPS branches of BridgeDb.

See:
https://github.com/bridgedb/BridgeDb/blob/OpenPHACTS/master/org.bridgedb.uri.sql/src/org/bridgedb/sql/SQLUriMapper.java
public IdSysCodePair toIdSysCodePair
And methods called from that.

There is even some support for the same uri pattern and overlapping or even the same regex pattern
 This would also be the place to add new rules if required.
