### ISSUE TITLE
datasources.tsv and other TSV files

### ISSUE THREAD

**Issue by ariutta** [bridgedb/BridgeDb#145]
In [this pull request](https://github.com/bridgedb/BridgeDb/pull/68#issuecomment-524858509), we decided to switch from `.txt` to `.tsv` for the files in [org.bridgedb.bio/resources/org/bridgedb/bio/](https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/). But at the moment, we still have both, and I notice they are not synced.

To avoid confusion, can we go ahead and replace the `.txt` files with the `.tsv` files? Or if that's not possible right away, can we automatically sync the `.txt` and `.tsv` files somehow whenever there's a new commit?

**Comment by AlexanderPico** [comment]
It's one thing to decide to switch, but it's another to actually perform the switch. Someone has to identify all the places in related and potentially 3rd party tools and use cases where the `.txt` is being used. Maybe there is 1 or 2. Maybe there are dozens??

Or, as mentioned, we have to now commit to maintaining both either manually (e.g., by convention) or by developing and maintaining a automated system.

My vote would be to just have one. Is it really worth having a tsv? Whomever it is "worth" having the tsv needs to take on the extra work.

**Comment by ariutta** [comment]
Primary reason to use TSV: it displays nicely autmatically on GH. I've made the change everywhere I can, but I think this is as far as I'll be taking it. If anyone wants to finish the switch, it's an open task.

**Comment by egonw** [comment]
I'll be on this as soon as possible. But in `master` please go ahead. As long as it compiles, that's where these things happen. Ideally, work in a branch, remove the file, see how many tests fail. We hope to have Jenkins online soon again.

**Comment by egonw** [comment]
Oh, yes, let's *remove* the .txt version.

**Comment by ariutta** [comment]
I notice the .txt and .tsv versions have diverged.

**Comment by egonw** [comment]
Fixed in master.
