### ISSUE TITLE
BridgeDb not working in Cytoscape 3.8.0?

### ISSUE THREAD

**Issue by remizallot** [bridgedb/BridgeDb#151]
Hi,
I would like to report that BridgeDB seems to not work with Cytoscape 3.8.0 on PC.

I just installed the latest version of Cytoscape 3.8.0 on Windows 10.
At the first Cytoscape launch, I installed BridgeDB using the Cytoscape app manager.

In the "Currently installed" tab of Cytoscape, BridgeDb 1.1.0.2 status is "Failed to Start".

Thanks you!

**Comment by egonw** [comment]
@AlexanderPico, can you plz have a look at this?

**Comment by egonw** [comment]
@remizallot, I am not an expert in Cytoscape (I use it about once a year actively), but understood the BridgeDb functionality is now core part of the Cytoscape and I am not sure if the BridgeDb app gives functionality that the core does not already. This is why I pinged Alex, but he seems to have missed this ping or simply not had time. @mkutmon, do you know if the BridgeDb app should be used with Cytoscape 3.8?

**Comment by AlexanderPico** [comment]
Here! Sorry for the delay. 

Right. My first question would be what are you trying to do? Most BridgeDb functionality is now built-in and the app is not needed at all. The app hasn't been touched in 6 years! I might just remove it from the app store...

**Comment by remizallot** [comment]
Hello,

Alexander, please do not delete the BridgeDB app. Some Cyotscape users
(like me) prefer to use older versions (pre 3.6).

I have been told that what I have been doing with BridgeDB is Cytoscape can
now be done directly in newer versions of Cytoscape. I have not tried it
yet.
There is information in the Cytoscape user manual about that (
http://manual.cytoscape.org/en/stable/Node_and_Edge_Column_Data.html).

I have used BridgeDB in Cytoscape to map specific attributes to specific
node IDs. We are speaking about adding attributes for 10 of thousands of
nodes at a time, from a tab formatted file that are automatically generated.

On that page (https://efi.igb.illinois.edu/training/videos.php), you can
hear me in the video "Adding Custom Node Attributes to a SSN" that explains
how I use Cytoscape and BridgeDB, on a small scale.

I am available and open to answer questions, if needed.

Best regards,
Remi Zallot


Le mer. 12 août 2020 à 19:42, Alexander Pico <notifications@github.com> a
écrit :

**Comment by remizallot** [comment]
Hello,

it looks like the BridgeDB app is not present in the app store any more.

This means that there is no way anymore to map IDs for earlier versions of
Cytoscape.

Is it possible to reinstate BridgeDB to be active on the App Store?
Otherwise, would it be possible me to obtain a copy so that I can manually
install it if needed?

Thank you


Le ven. 21 août 2020 à 23:27, Egon Willighagen <notifications@github.com> a
écrit :

**Comment by egonw** [comment]
@Chris-Evelo, is this something Lucas could look at?

**Comment by AlexanderPico** [comment]
I submitted a fixed version of the app on Sept 10th.
http://apps.cytoscape.org/apps/bridgedb

**Comment by egonw** [comment]
Oh, sorry, I missed that!

**Comment by Chris-Evelo** [comment]
About Lucas, he will write usage recipes for all the different implementations of BridgeDb which we will ask you to review. Of course, that might mean that he can stumble on more things that are no longer working.
