### ISSUE TITLE
Mismatches between datasources_headers.txt and BridgeDb vocab

### ISSUE THREAD

**Issue by ariutta** [bridgedb/BridgeDb#18]
The terms from [datasources_headers.txt](https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources_headers.txt) don't match their corresponding partners from the BridgeDb vocab. For example, datasources_headers.txt has `website_url` where the BridgeDb vocab has `mainUrl`.

**Comment by stain** [comment]
Agreed that these should be changed to match the [bridgeDB ontology](http://vocabularies.bridgedb.org/ops)

Note also that the alternate [RDF data sources](https://github.com/bridgedb/BridgeDb/tree/master/org.bridgedb.rdf/resources) (`*.ttl`) uses the bridgeDB ontology.

**Comment by egonw** [comment]
Marked for 2.2.0 (and not the stable release) because 2.2.0 is first to support RDF in full. (Makes sense?)

**Comment by ariutta** [comment]
I added an `@id` column. Is that change OK? Could you double-check the entries?
