### ISSUE TITLE
AbstractResolverTest.java class

### ISSUE THREAD

**Issue by hbasaric** [bridgedb/BridgeDb#214]
Bug with AbstractResolversTest.java class: maven running the test on mvn clean install, should be skipping since it is testing an abstract class (test fails when running mvn clean install)

**Comment by egonw** [comment]
@tabbassidaloii and I ran into this problem yesterday. It is weird that this shows up on a Windows OS, but not on Debian or Ubuntu. But we also found the solution yesterday.

**Comment by tabbassidaloii** [comment]
@egonw by mistake, I pulled the changes instead of sending a pull request :(
https://github.com/bridgedb/BridgeDb/commit/4ffda75ca2151886e085b7c617924c8346b2db1f

**Comment by egonw** [comment]
Yeah, this is why you can now block that on GitHub :)

No worries, and thanks for pushing the fix!
