### ISSUE TITLE
versions

### ISSUE THREAD

**Issue by IgorRodchenkov** [bridgedb/BridgeDb#22]
In the master branch, the project version in the pom.xml is 2.1.0-SNAPSHOT, which is behind already released 2.1.1. What does it mean?

PS:
Is bridgedb2.x the stable release branch? The version there is still 2.1.0-SNAPSHOT as well. 
Was it merged into the master?..
Do you want to eventually deploy/release to e.g., [OSSRH](http://central.sonatype.org/pages/ossrh-guide.html) public maven repository (and then to Maven Central)?

**Comment by egonw** [comment]
Hi Igor, more comments to follow...

1. At this moment Ant is still the official build system (which may cause the pom.xml version to be outdated)
2. master branch is under development (but will fix the version shortly)
3. once Maven is the main build system, then I do like to push to a central Maven repos (help welcome!)
4. master should be uptodate with respect to bridgedb2.x (just checked that the latest patches are included)
5. master shows a few regressions on Jenkins: https://jenkins.bigcat.unimaas.nl/job/bridgedb%20(with%20Ant)/lastCompletedBuild/testReport/ and https://jenkins.bigcat.unimaas.nl/job/bridgedb/lastCompletedBuild/testReport/

**Comment by egonw** [comment]
For now, I fixed the version numbers. Sorry for the inconvenience.
