### ISSUE TITLE
Replace onejar plugin

### ISSUE THREAD

**Issue by stain** [bridgedb/BridgeDb#32]
Build of `org.bridgedb.rdf` fails with:

> [INFO] BridgeDb RDF ....................................... FAILURE [  0.326 s]
> 
> [ERROR] Plugin org.dstovall:onejar-maven-plugin:1.4.4 or one of its dependencies could not be resolved: Could not find artifact org.dstovall:onejar-maven-plugin:jar:1.4.4 in onejar-maven-plugin.googlecode.com (http://onejar-maven-plugin.googlecode.com/svn/mavenrepo) -> [Help 1]

This repository is probably gone as Google Code is now shut down.

I think this `<plugin>`
https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.rdf/pom.xml#L15
should be replaced with a more regular uberjar plugin, e.g. `appassembler-maven-plugin` and/or `maven-shade-plugin`. 

For example, see https://github.com/apache/incubator-taverna-language/blob/master/taverna-tavlang-tool/pom.xml#L127

**Comment by stain** [comment]
..Or use the forked onejar plugin from https://github.com/jolira/onejar-maven-plugin (which is in Maven Central)

**Comment by randykerber** [comment]
Pushed a fix to branch "ops-2.2".  Named the version "2.2.0-ops-SNAPSHOT".

Dependency updated to the one @stain mentions above:  groupId = "com.jolira".

Feel free to fix up version names or anything else that ought to be changed.
(I'm not a maven expert).

**Comment by egonw** [comment]
Confirmed fixed.
