### ISSUE TITLE
missing probe identifiers?

### ISSUE THREAD

**Issue by egonw** [bridgedb/BridgeDb#35]
Jonathan, not sure if this is a bug, but why don't we see ID mappings for this probe ID?

![image](https://cloud.githubusercontent.com/assets/26721/20423322/e6961fd6-ad6f-11e6-89e3-0a4a7cab39f0.png)

This is from http://www.wikipathways.org/index.php/Pathway:WP370

**Comment by JonathanMELIUS** [comment]
The datanode with the label LCB2 is annotated with this id: S000002469 (SGD)
You can double check at the External references table at the bottom of the page.

This is a "known" issue related with the pvjs.

**Comment by egonw** [comment]
Ummm... yes, but in the table no mappings are given either...
