### ISSUE TITLE
Bump version to -SNAPSHOT

### ISSUE THREAD

**Issue by stain** [bridgedb/BridgeDb#41]
Why is the pom.xml on the `master` branch still saying `<version>2.2.0</version>` even though there's been quite a few commits since 2.2.0? The version should be bumped to `2.2.1-SNAPSHOT` or equivalent for all pom.files. 

Am I OK to do that?

**Comment by stain** [comment]
Or is 2.2.0 not yet existing? (no tag) In which case it should clearly say `2.2.0-SNAPSHOT`!

**Comment by egonw** [comment]
No, I was very close to a release, and then ran into the situation that the BridgeDb Derby files did not load in various situations... I will be less sloppy with versioning and even do preparing releases in a branch...

**Comment by egonw** [comment]
What do you think? "Revert" to 2.2.0-SNAPSHOT or never release 2.2.0 and aim at a 2.2.1 release?

**Comment by stain** [comment]
Ah, I caught you in the middle of the action.. :)    Revert to `2.2.0-SNAPSHOT` until the release is ready/tagged? 

Usually the `mvn release:prepare` and `mvn release:perform` will handle it for you. It can do it on a branch or as master commits with immediately bumps to the next `SNAPSHOT`  (the `2.2.0` commit would never stay at tip).

**Comment by egonw** [comment]
Is changing the root pom.xml version enough (which I just did)? I guess not...

**Comment by egonw** [comment]
Those two mvn commands seem useful... new to me (as much of Maven, really)... thanks!

**Comment by stain** [comment]
Try `mvn release:update-versions -DautoVersionSubmodules=true` to update all POMs in one go.

See https://maven.apache.org/maven-release/maven-release-plugin/update-versions-mojo.html

**Comment by stain** [comment]
https://maven.apache.org/maven-release/maven-release-plugin/index.html
https://maven.apache.org/maven-release/maven-release-plugin/examples/prepare-release.html
https://maven.apache.org/maven-release/maven-release-plugin/examples/perform-release.html

For this to work the `<scm>` info needs to be up to date (it seems to be)
