### ISSUE TITLE
linkset paths wrong for ensembl mus musculus

### ISSUE THREAD

**Issue by ianwdunlop** [bridgedb/BridgeDb#61]
In ensemble mus musculus linkset files there is an inconsistency between what the linkset path is and what the actual path should be.

`http://bridgedb.org/data/linksets/MusMusculus/release87`
should be
`http://bridgedb.org/data/linksets/release87/MusMusculus`

'release87' should be before 'MusMusculus'.

**Comment by egonw** [comment]
Patch put in place, but needs confirmation that the problem is fixed now.
