### ISSUE TITLE
datasources.txt Uniprot identifiers causes IMS to fail

### ISSUE THREAD

**Issue by ianwdunlop** [bridgedb/BridgeDb#66]
Commit 2d248d637ff6fe6285fcf34f89d9fe22a2326a67 changed the `org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt` file as follows:

-Uniprot-SwissProt Sp http://www.uniprot.org/ http://www.uniprot.org/uniprot/$id CALMHUMAN protein 1 Sp ^[A-Z0-9]+[A-Z]+$ UniProtKB/Swiss-Prot
+Uniprot-SwissProt Sp http://www.uniprot.org/ http://www.uniprot.org/uniprot/$id CALMHUMAN protein 1 urn:miriam:uniprot
^[A-Z0-9]+[A-Z]+$ UniProtKB/Swiss-Prot

The Uniprot `code` was changed from Sp to urn:miriam:uniprot. This causes the IMS to fail when parsing uniprot URIs:

Error handling: (http://www.conceptwiki.org/concept/5fa40ec7-c73f-4810-a5c7-3743970b02ec, http://www.w3.org/2004/02/skos/core#exactMatch, http://www.uniprot.org/uniprot/O14329) org.bridgedb.utils.BridgeDBException: Uri http://www.uniprot.org/uniprot/O14329 maps to two different regex patterns http://www.uniprot.org/uniprot/$id (^([A-N,R-Z][0-9]([A-Z][A-Z, 0-9][A-Z, 0-9][0-9]){1,2})|([O,P,Q][0-9][A-Z, 0-9][A-Z, 0-9][A-Z, 0-9][0-9])(\.\d+)?$) for DataSource Sp and http://www.uniprot.org/uniprot/$id (^([A-N,R-Z][0-9][A-Z][A-Z, 0-9][A-Z, 0-9][0-9])|([O,P,Q][0-9][A-Z, 0-9][A-Z, 0-9][A-Z, 0-9][0-9])(\.\d+)?|([A-N,R-Z][0-9][A-Z][A-Z, 0-9][A-Z, 0-9][0-9][A-Z][A-Z, 0-9][A-Z, 0-9][0-9])$) for DataSource S

Apparently the change was necessary because "MIRIAM does not distinguish SwissProt from TrEMBL". Does this mean that we should ask MIRIAM to change something on their end or do we need to do something with the identifier patterns or BridgeDB/IMS code?
We really need this code to work or else we will need to fork an Open PHACTS version of BridgeDB and deploy that. Then we will have 2 versions of BridgeDB which is not an ideal situation.

**Comment by ariutta** [comment]
The error could be located in one of several places. I'll describe what I'm trying to do, and maybe you can help pinpoint the source of the problem.

Goal: convert WikiPathways `Xrefs` to Miriam/identifiers.org IRIs.

Example: pathway [WP3998](https://www.wikipathways.org/index.php/Pathway:WP3998) has this element in its GPML:
```xml
<Xref Database="Uniprot-SwissProt" ID="P24385" />
```

I thought I could use [datasources.txt](https://github.com/bridgedb/BridgeDb/blob/bbb29bdf6a083f5d0f17410367d65381e16df556/org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt) to map from GPML `Database` to Miriam/identifiers.org `namespace`. According to [datasources_headers.txt](https://github.com/bridgedb/BridgeDb/blob/bbb29bdf6a083f5d0f17410367d65381e16df556/org.bridgedb.bio/resources/org/bridgedb/bio/datasources_headers.txt), `Database` corresponds to `datasource_name`, which is the first column of datasources.txt. The ninth column of datasources.txt, `uri`, is:
> Official URI for datasource (e.g., from miriam); or repeat of system_code if unknown or unregistered

These are the potential fixes I see:
1) WikiPathways should only use `Uniprot-TrEMBL`, not `UniProtKB/Swiss-Prot`
2) datasources.txt should list `urn:miriam:uniprot` for `UniProtKB/Swiss-Prot`
3) identifiers.org should create a new namespace for `UniProtKB/Swiss-Prot`

Supporting 1), it seems that at WikiPathways, all Xrefs with `Database` values of `UniProtKB/Swiss-Prot` have `ID` values that match the datasources.txt regex for `Uniprot-TrEMBL`, not for `UniProtKB/Swiss-Prot`.

Supporting 2), identifiers.org [states](https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000005) that `UniProtKB/Swiss-Prot` is an alternative name for namespace `uniprot`. That means the Miriam/identifiers.org URI for `Uniprot-SwissProt` is registered. If that's true, then according to datasources_headers.txt, the ninth column should be `urn:miriam:uniprot` for `Uniprot-SwissProt`.

Supporting 3), the URI `http://identifiers.org/uniprot/CALM_HUMAN` fails to resolve. `CALM_HUMAN` is the example identifier listed for `UniProtKB/Swiss-Prot` in datasources.txt.

**Comment by AlexanderPico** [comment]
I think we should reverse the [problematic change](https://github.com/bridgedb/BridgeDb/commit/2d248d637ff6fe6285fcf34f89d9fe22a2326a67) right away to get IMS working again.

@ariutta Could you use the UniProt-TrEMBL row in datasources.txt for both swissprot and uniprot mappings in the meantime?

Longer term, we could explore other solutions involving miriam updates or adding another column to datasources or converting all swissport refs to uniprot (when using accessions), etc.

**Comment by egonw** [comment]
This is the remaining patch in the OPS master left in the merge and pertains to this issue:

https://github.com/openphacts/BridgeDb/commit/fa325723886a4e0c9fbd8fd4bd76e2adb9a95345

**Comment by egonw** [comment]
Closed by https://github.com/bridgedb/BridgeDb/commit/192a18f2ee626279b0845a597b5861f02fe8e521
