### ISSUE TITLE
more than one datasource with "urn:miriam:uniprot" is causing trouble

### ISSUE THREAD

**Issue by egonw** [bridgedb/BridgeDb#67]
See this change back and forth: https://github.com/openphacts/BridgeDb/commit/bbb29bdf6a083f5d0f17410367d65381e16df556

Apparently there cannot be two data sources with the same MIRIAM urn prefix at this moment...

**Comment by egonw** [comment]
See also #58

**Comment by ariutta** [comment]
Also #17

**Comment by ariutta** [comment]
See also #62 and #66.

**Comment by ariutta** [comment]
See also #66.

**Comment by egonw** [comment]
Closed by https://github.com/bridgedb/BridgeDb/commit/192a18f2ee626279b0845a597b5861f02fe8e521
