### ISSUE TITLE
Swagger on BridgeDb docker image

### ISSUE THREAD

**Issue by marvinm2** [bridgedb/BridgeDb#70]
Are the files that create the swagger interface within the code of BridgeDb? In order to use BridgeDb swagger as part of the docker image (https://github.com/bridgedb/docker) it should be within the bridgedb repository. Is this the case? Also, would like to see if we can configure this with the locally downloaded mapping databases and run the swagger locally.

**Comment by egonw** [comment]
@nunogit, @marvinm2, where in the code (filename, line) is the one-line change?

**Comment by egonw** [comment]
ping @marvinm2, @nunogit, what is the state of this issue?

**Comment by nunogit** [comment]
@egonw I have to check the repo. As far as I know it was solved, but I might be wrong.
