### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ariutta** [bridgedb/BridgeDb#77]
just noticed this page is outdated: http://www.bridgedb.org/mapping-databases/rhea-interaction-mappings/

this link is old and broken: http://bridgedb.org/data/gene_database/archive/r82/interactions_20160108.bridge.zip
should it point here? http://developers.pathvisio.org/data/gene_database/interactions_20180425.bridge

**Comment by egonw** [comment]
Believed to be fixed.
