### ISSUE TITLE
Link out to GeneWiki

### ISSUE THREAD

**Issue by egonw** [bridgedb/BridgeDb#84]
There currently is only a link out to WikiGenes (cc @Chris-Evelo, @AlexanderPico).

**Comment by Chris-Evelo** [comment]
Technically GeneWiki is the WikiPedia presence of NCBI genes (which we do have). I think if ENSEMBL decides to include GeneWiki we should add it too (maybe they already did, otherwise we could ask them). Using mixed resources to build a BridgeDb database, in general, can cause problems. I would not think this is worth that extra complication.

**Comment by egonw** [comment]
GeneWiki is the project of Andrew and Andra, and am willing to make the creating a bit more complex for just that reason.

**Comment by Chris-Evelo** [comment]
True, but I would still prefer to ask ENSEMBL whether they want to add it first (if they haven't already). In part even for the same reason. It will be beneficial for GeneWiki if they are referenced from GeneWiki. BTW the project started long before Andra started to work for them and I think most work was done by Ben Good. Warren Kibbe was also involved. Note that given the model GeneWiki uses,  links to WikiPedia should also cover it. I actually thought we already had these.

**Comment by egonw** [comment]
Agreed, if Ensembl would do that, that would be wonderful! Ping @andrawaag, did that already get discussed between GeneWiki and Ensembl?

**Comment by egonw** [comment]
I like to strengthen our collaborations, particularly when they are around open science. If that means I need to complement Ensembl (would be great if they started linking out to Wikidata!) with data from GeneWiki, I see no problems with that. I find it strange that we would not collaborate with Andra on GeneWiki (yes, of course, including everyone on that team that is or was involved) because Ensembl does not.
