### ISSUE TITLE
Build org.bridgedb.tools.qc from regular build

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/BridgeDb#90]
The org.bridgedb.tools.qc library now has to be build separately (not part of dist folder after regular build).

**Comment by DeniseSl22** [comment]
It's still not being built when building with Maven (using mvn clean install). The only jars as output I get is:
![image](https://user-images.githubusercontent.com/26277832/63085527-05f7f000-bf4e-11e9-885a-0112da384e39.png)

Furthermore, the ant build doesn't seem to work anymore. When I run:
```
ant build
```
In the command line, I get the following output: 
![image](https://user-images.githubusercontent.com/26277832/63085484-ee206c00-bf4d-11e9-9562-c46febcd5840.png)

Not sure what is going wrong here, but it would be good to include the QC.jar in the mvn build as well....

**Comment by The-Marvex** [comment]
I was able to build the master branch with maven although I did get the same exception on Ant. Working on that and I'll create a pull request asap.

**Comment by DeniseSl22** [comment]
@The-Marvex okay great thank you for looking into this! Does your Maven build also create a org.bridgedb.tools.qc.jar ? For me it doesn't (which was the original purpose of this issue).

**Comment by egonw** [comment]
@DeniseSl22, it creates a `org.bridgedb.tools.qc/target/org.bridgedb.tools.qc-${VERSION}.jar` and the `qc.sh` bash script is updated for that.
