### ISSUE TITLE
New HMDb IDs are not recognised

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/BridgeDb#91]
GET /{organism}/xrefs/{systemCode}/{identifier} call:

For the [bridgedb test webservice](http://137.120.17.99/swagger/​), I could convert the old HMDb-IDs to others; however the new IDs all gave N/A as a value. I'm not sure if this is because of old mapping files behind the webservice, or if something else is going on?
I used the following IDs:
HMDB0000112
HMDB0000295
HMDB0000901
HMDB0000935
HMDB0001275
HMDB0001877
HMDB0013037

Results: 
![image](https://user-images.githubusercontent.com/26277832/55084969-22ca7e80-50a6-11e9-881a-f5b2c5490f75.png)

**Comment by nunogit** [comment]
Can that be related with the database version?
This is not the most recent yet.

**Comment by DeniseSl22** [comment]
Yeah could be, Where can I check which data is behind the webservice :)?

**Comment by nunogit** [comment]
@DeniseSl22  You can check ensenbl version in {species}/properties

**Comment by nunogit** [comment]
Most likely a version problem. The databases I am running are from 2013 (probably the ones used in WikiPathways?). These were the ones sent by Alex.
Never thought it would be so different if that's the case. In any case I already discussed with Alex bringing it to the latest version.

**Comment by nunogit** [comment]
I am closing this issue and reopening one to install the latest version.
