### ISSUE TITLE
Metabolite query gives 502 error

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/BridgeDb#92]
GET /{organ­ism}/xrefs/{systemCode}/{identifier}
The example ID(CHEBI:29108) for the first metabolite query gives a 502 error:

![image](https://user-images.githubusercontent.com/26277832/55085278-b0a66980-50a6-11e9-9f93-5d70f56d0850.png)

**Comment by nunogit** [comment]
Very curious. That happens with all Ce id's
In the live version it doesn't.
I will check the proxy.

**Comment by nunogit** [comment]
Solved. The server died :( 
It's working again.
