### ISSUE TITLE
Install latest bridgedb databases in new server

### ISSUE THREAD

**Issue by nunogit** [bridgedb/BridgeDb#93]
Based on #91

**Comment by DeniseSl22** [comment]
Yes, latest versions can be found here: https://www.bridgedb.org/mapping-databases/ . I can also upload the metabolite and interaction mapping files to a server (if needed).... but the server I used to upload too, doesn't have that much room left. Has this been solved already?

wget -c -O metabolites_20190207.bridge https://ndownloader.figshare.com/files/14298554
wget -c -O : interactions_20190228.bridge https://ndownloader.figshare.com/files/14488412
