### ISSUE TITLE
Update QC for IUPHAR (Guide to Pharmacology)

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/BridgeDb#96]
The QC report does not recognise Gpl as a Datasource:
![image](https://user-images.githubusercontent.com/26277832/56145293-4fd2c880-5fa4-11e9-881b-a915aa96a948.png)

Where should I change the datasources, so that the QC prints the name of the Datasource (since the SysCode seems to be recognised....)

**Comment by egonw** [comment]
OK, I cannot reproduce this. Are you sure your QC tool is using a BridgeDb library that has the data set defined? Like 2.4.0?

**Comment by DeniseSl22** [comment]
Yeah, I will remove my bridgedb folder, pull it again and build it again (this time with maven). If I then still have the problem, I let you know!
